### ISSUE TITLE
Can't update belongsToMany relationship

### ISSUE THREAD

**Issue by KenoKokoro** [FrozenNode/Laravel-Administrator#784] opened 2014-12-21 12:11 UTC
I have two tables hotels and facilities connected with third table hotels_facilities. They are connected with belongsToMany relationship. Everything works good, I can add new facilities on the hotel, I can preview them, but I can't edit them. When I click the save button on chrome debugger in network tab I get 500 Internal Server Error with this message: "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hotel_id' cannot be null (SQL: insert into `hotels_facilities` (`facility_id`, `hotel_id`) values (3, ))". I have the same problem with rooms and facilities. But on new clean laravel installation I did the tutorial with the books and topics, and everything worked well there, but I have this error on my project.
Any idea what is the problem?
Thanks in advance

**Comment by KenoKokoro** [comment] 2015-01-12 12:04
Yes, the relationship is set up correctly, but it gives this error:
 "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hotel_id' cannot be null (SQL: insert into hotels_facilities (facility_id, hotel_id) values (3, ))"
As you can see, in values there is no value for hotel_id. This is confusing me and also is not working properly, I can create new but I can't update existing one.

**Comment by amanpatel** [comment] 2015-01-12 15:43
Since this is an old issue, if this is still happening, it would be good to have more information. Consider providing the following:

1) Full listing of reproduction steps that leads to that sql being executed in your log.

2) Perhaps the administrator config file for that model that calls for this sql.

3) the relationship definition functions linking the two models.

I'm using several pivot relationships in my app and none have caused this errors. There has got to be something environment related that is causing this error for you.

**Comment by KenoKokoro** [comment] 2015-01-14 15:12
Okay, lets start over again:
I have table hotels, where I have all the hotels.
I have other table facilities, where I have all the facilities breakfast, parking, pets, wifi... etc.
I am linking them with facility_hotel table. I am using this in Hotel model:
	**public function facilities() {
		return $this->belongsToMany('Facility');
	}**
I am listing them in the **edit_fields** array like this:
**'facilities' => array(
			'title' => 'Facilities',
			'type' 	=> 'relationship',
			'name_field' 	=> 'facility',
		),**

Everything is good when I create a new record. The record is successfully written on database, I can preview the facilities when I click to edit existing record of hotel.
I got the error from above when updating an existing one
The error I am getting from the post method doing while saving the record. 
**file: "D:\Sublime Text\Development\DEV_AltaTurs\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
line: 625
message: "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hotel_id' cannot be null (SQL: insert into `facility_hotel` (`facility_id`, `hotel_id`) values (1, ))"
type: "Illuminate\Database\QueryException"**
I really don't know what is wrong. I am doing this on fresh installation of Laravel 4.2 like the tutorial with the books and topics, and everything works really smooth.

**Comment by parabol** [comment] 2015-01-14 15:30
Hi,

You have an error because of your facility_hotel table. you should modify the fields which you try to leave "null".

please note that;
 if you try to insert related data for your tables, you should have to assign both "objects" to $vars. Then insert with eloquents ORM's way.

**Comment by KenoKokoro** [comment] 2015-01-14 15:57
If i leave it the field 'null' I get records in database but I have null value for hotel_id and it doesn't work because I can't know what hotel I am using in that fields.

**Comment by KenoKokoro** [comment] 2015-01-16 09:46
and also, how can I assign both "objects" to $vars? I am confused by this?

**Comment by krodyrobi** [comment] 2015-01-19 16:53
I can confirm this is still happening, when using in conjuncture with [Entrust](https://github.com/Zizaco/entrust). 

Current setup:
[Migration](http://pastebin.com/H5t4qEWM)
[Admin Config](http://pastebin.com/9T0BRp24)
[Role](http://pastebin.com/YjhZYhqu)
Permission: Default EntrustPermission
[EntrustPermission](https://github.com/Zizaco/entrust/blob/39c611945b6355904d8c9ece3cee9b861d0145d9/src/Entrust/EntrustPermission.php)
[EntrustRole](https://github.com/Zizaco/entrust/blob/39c611945b6355904d8c9ece3cee9b861d0145d9/src/Entrust/EntrustRole.php)

How to replicate:
Create a new Role, assign it some permissions => save (OK)
Edit the new Role, remove some permissions    => save (Integrity error)
Edit the new Role, add more permissions, to the same faulty Role => save (Integrity error)

Although the DB has no row for the faulty removed items, so i'm guessing the update happens in the wrong order, don't take my suspicion for granted cause I'm a laravel n00b :D.

Also from the same owner  [Confide](https://github.com/Zizaco/confide), the user creation works, but can't seem to be able to edit any field :|. If anyone can help that would make my day, Thanks!

**Comment by KenoKokoro** [comment] 2015-01-26 10:05
Anyone help with this problem, please?
Thanks.

**Comment by parsnick** [comment] 2015-02-10 13:45
I'm also having this problem. I *think* it's caused by the logic in `Frozennode\Administrator\Config\Model\Config::fillModel()` that unsets all non-editable fields from the model instance, including the primary key. When it then tries to update the relationships, the primary key is missing, producing the error noted here.

As a horrible workaround, I've resorted to making the primary key an editable field in my model config and I no longer have the error.

**Comment by davemathews** [comment] 2015-09-26 05:48
Is this all being done on a postgres or mysql databases?

**Comment by krodyrobi** [comment] 2015-09-26 06:08
In my case it was a mysql database.

**Comment by davemathews** [comment] 2015-09-26 06:55
@krodyrobi is it still happening for you?  What version of laravel? What version of Administrator? Can you post your models and model configs?

**Comment by davemathews** [comment] 2015-10-29 13:56
closing due to inactivity reopen if you have more information

**Closed by davemathews** 2015-10-29 13:56 UTC
Labels: not enough information
